### ISSUE TITLE
开机登录分辨率问题

### ISSUE THREAD

**Issue by wanglelecc** [szc188/MSI-B460M-MORTAR-10700K-5500XT-OC#1]
感谢大佬的 EFI 分享顺利吃上黑果
1. BIOS 设置里还需要关闭 ”MIS 快速启动“ 选项，不然启动后一直加载重启，过不去。
2. 开机启动登录页分辨率问题，在系统里面设置了缩放(3008 x 1692)，登录页的显示的是 1080P，进入桌面的时候回卡一下，然后才能正常。 Config—–UEFI—-Output  Resolution 调整没什么效果。不知道您这边有没有此现象？

**Comment by szc188** [comment]
1. 好的感谢，已经加到Readme里去了
2. 我分别用老版本和新版本测试了一下，老版本下将系统设置为缩放(3008 x 1692)后，重启在进度条走完跳到输入密码前会黑屏卡死，但是重启后就正常了，输入密码界面是1080P的，进入桌面会切换一下分辨率；今天的新版本下测试了一下没有出现黑屏卡死的情况，不过进入桌面依然会切换一下分辨率；考虑可以调整 `UIScale` 为 `1`，重启CleanNvram一下应该就不会切换分辨率了（没有测试过）

**Comment by OptimusV5** [comment]
分享下，我的是把UIScale设置为2，Resolution设置为Max，体验完美（开机无黑屏，两个苹果大小一致且适中），不过我是3840*2160的显示器
