### ISSUE TITLE
求升级

### ISSUE THREAD

**Issue by jia-github-pro** [szc188/MSI-B460M-MORTAR-10700K-5500XT-OC#11]
作者您好。现在oc已经到0.6.8版本了，能麻烦升级一下吗？

**Comment by szc188** [comment]
您好，我发现github上有类似的项目一直在持续更新，我这边暂时就停更了，你可以去试试他的

**Comment by szc188** [comment]
[https://github.com/myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630](url)
