### ISSUE TITLE
可以把 i7-10700k 换成  i7-10700 吗？

### ISSUE THREAD

**Issue by SuvanCheng** [szc188/MSI-B460M-MORTAR-10700K-5500XT-OC#2]
我用的先马趣造，感觉i7-10700k在小机箱里施展不开

**Comment by szc188** [comment]
同代u应该可以的，你可以试试
我也用的m-atx的小机箱还不错

**Comment by SuvanCheng** [comment]
| 型号 | 价格
-- | -- | --
CPU | i7 10700 | 2299
GPU | RADEON RX5600XT | 2049
MotherBoard | MSI B460M MORTAR | 679
SSD | WD Blue SN550 1T | 745
Memory | CUSO 16GB 2666 | 239
Memory | CUSO 16GB 2666 | 239
Power | Segotep GP750G 650w | 359
Case | SAMA mini | 289
Radiator | ID-COOLING SE-50 | 139
  | TF8 | 34.9
总价 |   | 7071.9


用大佬的EFI直接安装成功！
