### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by OptimusV5** [szc188/MSI-B460M-MORTAR-10700K-5500XT-OC#4]
大佬有没有尝试升级到11.0.1 Big Sur? 求分享体验

**Comment by szc188** [comment]
还没时间尝鲜诶，据说PD还用不了，作为生产力还得过段时间

**Comment by jia-github-pro** [comment]
大佬，我用你的EFI完整装好了， 我直升了big sur，目前没看到任何问题，放心升级吧！

**Comment by szc188** [comment]
哇哦  那我改天也尝试尝试😀😀😀

**Comment by OptimusV5** [comment]
> 大佬，我用你的EFI完整装好了， 我直升了big sur，目前没看到任何问题，放心升级吧！

请问 随航 handoff之类的功能也是正常的是吧？

**Comment by OptimusV5** [comment]
> > 大佬，我用你的EFI完整装好了， 我直升了big sur，目前没看到任何问题，放心升级吧！
> 
> 请问 随航 handoff之类的功能也是正常的是吧？

我冲了，都没问题，不过handoff在重置了nvram之后才行，不知道是不是个例～

**Comment by SuvanCheng** [comment]
> 大佬，我用你的EFI完整装好了， 我直升了big sur，目前没看到任何问题，放心升级吧！

直升？！真厉害！

**Comment by jia-github-pro** [comment]
> > 大佬，我用你的EFI完整装好了， 我直升了big sur，目前没看到任何问题，放心升级吧！
> 
> 直升？！真厉害！

没问题的，安心升级
