### ISSUE TITLE
独显显存爆满的问题

### ISSUE THREAD

**Issue by joey-fudan** [szc188/MSI-B460M-MORTAR-10700K-5500XT-OC#6]
兄弟感谢你的配置, 我安装成功了:
<img width="578" alt="Screen Shot 2020-12-09 at 1 01 25 PM" src="https://user-images.githubusercontent.com/44150636/101587235-b5e44d00-3a1e-11eb-83fe-5e335c8ed5d2.png">

# 我的机器配置如下
- 主板：微星 MSI MAG B460M MORTAR
- CPU：Intel i7 10700
- 显卡: 蓝宝石RX 5500 XT 8G D6 白金版OC
- 电源: 安钛克 Antec NE550金牌全模组
- 显示器: 优派 24VX2478-4K-HD
- WiFi + 蓝牙: BCM94360CS2(1200M黑苹果免驱版)
- 内存: 金士顿(Kingston) DDR4 2666 8GB*2

# 一点改进
我更换了PciRoot(0x0)/Pci(0x2,0x0)下的device-id为0x3E9B8086, 跟Platform ID 0x3E9B0007是匹配的(Hackintool推荐的); 
<img width="652" alt="Screen Shot 2020-12-09 at 12 54 24 PM" src="https://user-images.githubusercontent.com/44150636/101586986-18891900-3a1e-11eb-92de-a38aab66358b.png">
GeekBench5也可以顺利读出来核显:
<img width="536" alt="Screen Shot 2020-12-09 at 12 55 24 PM" src="https://user-images.githubusercontent.com/44150636/101587028-30609d00-3a1e-11eb-86f9-753d1a6cb94c.png">

# 问题
用了一段时间后, 看iStat-menus发现独显的显存一直是满的:
<img width="967" alt="Screen Shot 2020-12-09 at 1 00 02 PM" src="https://user-images.githubusercontent.com/44150636/101587141-7b7ab000-3a1e-11eb-97db-17875757a02b.png">
不知道你有没有碰到这个情况?

**Comment by szc188** [comment]
好的  改了id后可以在GeekBench5中读出核显的型号了  不改也不影响核显的硬件加速

显存爆满貌似是系统机制的问题，即使显存满了也可以正常运行游戏看视频什么的，应该是有自动释放的

在切换屏幕分辨率的时候会自动释放显存，但是过一会儿依然会到99%

![image](https://user-images.githubusercontent.com/40622377/101592121-b08c0000-3a28-11eb-859a-26e4237a7362.png)

**Comment by joey-fudan** [comment]
另外, 最小化窗口的时候dock会经常会出现白色的斑纹(截图截不出来, 每次调用截图的时候它又消失了), 然后还有就是放缩窗口的时候稍微有点卡, 是不是独显设置有问题?

**Comment by szc188** [comment]
斑纹暂时没有遇到过，浏览器缩放的时候有时候会有点卡顿（页面元素多的时候或有GPU应用在运算的时候）

然后更新到BigSur后左右切换桌面的时候有时候会不流畅（使用虚拟机的时候）

独显是免驱的，在oc里就加了一句侦测的语句，应该不太可能有问题
