### ISSUE TITLE
升级big sur后/proc文件夹消失了

### ISSUE THREAD

**Issue by joey-fudan** [szc188/MSI-B460M-MORTAR-10700K-5500XT-OC#7]
老哥我又来了, 我早上刚升级了big sur, 系统用着都挺舒服的, hackintool信息都读的出来的
<img width="580" alt="Screen Shot 2020-12-14 at 1 53 25 PM" src="https://user-images.githubusercontent.com/44150636/102045385-df80e800-3e13-11eb-9629-8948345d2ec6.png">

但是发现screenfetch读不出来系统信息, 根目录下/proc消失了...
<img width="941" alt="Screen Shot 2020-12-14 at 1 52 07 PM" src="https://user-images.githubusercontent.com/44150636/102045262-94ff6b80-3e13-11eb-8760-0770c3c1feb6.png">

你们有遇到这个情况吗?

**Comment by szc188** [comment]
据我所知，MacOS上貌似没有实现procfs，所以这个版本不能在MacOS上使用

不过你可以尝试一下使用homebrew安装的screenfetch
```bash
brew install screenfetch
```

**Comment by joey-fudan** [comment]
找到原因了, https://github.com/KittyKatt/screenFetch/issues/680, 估计他们很快就会修复.
运行screenfetch -D 'Mac OS X'就没问题
<img width="941" alt="Screen Shot 2020-12-14 at 2 16 29 PM" src="https://user-images.githubusercontent.com/44150636/102046797-0987d980-3e17-11eb-8735-42fed366c5d5.png">
