### ISSUE TITLE
Big Sur 11.2.1 直升成功，除了虚拟机不能联网需要改动参数外，其他一切OK

### ISSUE THREAD

**Issue by SuvanCheng** [szc188/MSI-B460M-MORTAR-10700K-5500XT-OC#8]
直升除去下载时间，共耗时33分钟；
点击升级后，无需其他操作；

#问题：
###Parallels Desktop 16
网络初始化失败：您的虚拟机将继续正常运作，但将无法连接网络

###Solution
1. sudo nano /Library/Preferences/Parallels/network.desktop.xml 
2. find <UseKextless>1</UseKextless> (value can be -1), and change the value to the <UseKextless>0</UseKextless> 
3. if you can't find this tag, then just create it under root tag <ParallelsNetworkConfig ...>here</ParallelsNetworkConfig>

**Comment by szc188** [comment]
尝试了一下网上的修复pd的网络连接和usb问题的解决方法，网络正常，也能使用usb存储设备，但是u盾以及其他usb设备用不了
