### ISSUE TITLE
我这个配置能不能用的OC文件？

### ISSUE THREAD

**Issue by Niofh** [szc188/MSI-B460M-MORTAR-10700K-5500XT-OC#9]
电脑型号	微星 MS-7C82 台式电脑  (扫描时间：2021年02月21日)
操作系统	Windows 10 64位 ( DirectX 12 )
	
处理器	英特尔 Core i5-10400F @ 2.90GHz 六核
主板	微星 MAG B460M MORTAR (MS-7C82) ( LPC Controller - A3C8 )
内存	16 GB ( 金士顿 DDR4 2666MHz )
主硬盘	西数 WDS500G3X0C-00SJG0 ( 500 GB / 固态硬盘 )
显卡	AMD Radeon RX 5600 XT ( 6 GB / 迪兰 )
显示器	飞利浦 PHLC155 PHL 243V7 ( 23.8 英寸  )
声卡	瑞昱  @ 英特尔 High Definition Audio 控制器
网卡	瑞昱 Realtek PCIe 2.5GbE Family Controller / 微星

**Comment by szc188** [comment]
目测可以
